### Configs ###

# Data Configs
data:
  dataroot: 
    train: ./data/VOCdevkit/VOC2012/JPEGImages
    val: ./data/VOCdevkit/VOC2012/JPEGImages
    test: ./data/VOCdevkit/VOC2012/JPEGImages
  annotationroot: 
    train: ./data/VOCdevkit/VOC2012/SegmentationClass
    val: ./data/VOCdevkit/VOC2012/SegmentationClass
    test: ./data/VOCdevkit/VOC2012/SegmentationClass
  annotationpath: 
    train: ./data/VOCdevkit/VOC2012/ImageSets/Segmentation/train.txt
    val: ./data/VOCdevkit/VOC2012/ImageSets/Segmentation/trainval.txt
    test: ./data/VOCdevkit/VOC2012/ImageSets/Segmentation/val.txt
  img_size: [32, 32]
  n_channels: 3
  color_mean: [0.4914, 0.4822, 0.4465]
  color_std: [0.2023, 0.1994, 0.2010]
  label_color_map:  [[0, 0, 0],
                        [128, 0, 0],
                        [0, 128, 0],
                        [128, 128, 0],
                        [0, 0, 128],
                        [128, 0, 128],
                        [0, 128, 128],
                        [128, 128, 128],
                        [64, 0, 0],
                        [192, 0, 0],
                        [64, 128, 0],
                        [192, 128, 0],
                        [64, 0, 128],
                        [192, 0, 128],
                        [64, 128, 128],
                        [192, 128, 128],
                        [0, 64, 0],
                        [128, 64, 0],
                        [0, 192, 0],
                        [128, 192, 0],
                        [0, 64, 128],
                        ]
# Training Configs
train:
  batch_size: 8
  epochs: 50
  optimizer:
    type: adam
    lr: 0.0001
    decay: 0.0001
  criterion:
    type: cross_entropy
  n_gpus: 1
  save_ckpt_interval: 10

# Model Configs
model:
  name: fcn_resnet50
  n_classes: 21
  pretrained: False
  resume: 
    # e.g) resume: ./logs/2020-07-26T00:19:34.918002/ckpt/best_acc_ckpt.pth if resume. Blank if not resume

# Other Configs
util:
  logdir: ./logs/